server:
  port: 8080
  servlet:
    context-path: /
spring:
  r2dbc:
    name: r2dbc
    url: r2dbc:mysql://localhost:3306/goodhabbit
    username: root
    password: root
    pool:
      enabled: true
      initialSize: 100
      maxSize: 100
      validation-query: select 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  redis:
    host: localhost
    port: 49153
    password: redispw
    lettuce:
      pool:
        max-idle: 500
        min-idle: 0
        max-active: 1000
        max-wait: -1
    timeout: 5000

logging:
  level:
    root: DEBUG
    javax.activation: info
    org.springframework.r2dbc: DEBUG
    org.apache.catalina: INFO
    org.apache.commons.beanutils.converters: INFO
    org.apache.coyote.http11.Http11Processor: INFO
    org.apache.http: INFO
    org.apache.tomcat: INFO
    # 开启调试模式，打印sql
    io.bridge.test: DEBUG


